config/routes.rb
Rails.application.routes.draw do  
  devise_for :admins, path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: 'admins/sessions' }, skip: [:registrations, :passwords]
  namespace :admins do
    get 'edit' => 'registrations#edit'
    post 'update' => 'registrations#update'
    resources :dashboards, only: :index    
    resources :users
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }
      post 'sign_up' => 'registrations#create', as: :sign_up

      #master data
      resources :master_datas, only: [:index] do
        collection do
          get :stores
          get :products
        end
      end

      resources :carts, only: [:show] do
        put 'add/:variant_id', to: "carts#add", as: :add_to
        put 'remove/:variant_id', to: 'carts#remove', as: :remove_from
        put 'remove_one/:variant_id', to: 'carts#removeone', as: :remove_one
      end

      resources :transactions, only: [:new, :create]
      resources :orders, only: [:index]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/admins/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/admins/_header.html.erb
<header class="topbar">
  <nav class="navbar top-navbar navbar-expand-md navbar-dark">
    <div class="navbar-header skin7">
      <!-- This is for the sidebar toggle which is visible on mobile only -->
      <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
          class="ti-menu ti-close"></i></a>
      <!-- ============================================================== -->
      <!-- Logo -->
      <!-- ============================================================== -->
      <a class="navbar-brand" href="<%= admins_dashboards_url %>">
        <!-- <strong>Duedi</strong> -->
        <!-- Logo icon -->
        <b class="logo-icon">
          Admin
          <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
          <!-- Dark Logo icon
          <img src="<%#= asset_path("Duedi-Logo-White.png") %>" alt="homepage" class="dark-logo" style="width: 50px;" />-->
          <!-- Light Logo icon
          <img src="<%#= asset_path("Duedi-Logo-White.png") %>" alt="homepage" class="light-logo" style="width: 50px;" />-->
        </b>
        <!--End Logo icon -->
        <!-- Logo text
        <span class="logo-text">-->
          <!-- dark Logo text
          <img src="<%#= asset_path("Duedi-Logo-White.png") %>" alt="homepage" class="dark-logo" style="width: 100px;" />-->
          <!-- Light Logo text
          <img src="<%#= asset_path("Duedi-Logo-White.png") %>" class="light-logo" alt="homepage" style="width: 100px;" />
        </span>-->
      </a>
      <!-- ============================================================== -->
      <!-- End Logo -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Toggle which is visible on mobile only -->
      <!-- ============================================================== -->
      <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
        data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
    </div>
    <div class="navbar-collapse collapse" id="navbarSupportedContent">
      <!-- ============================================================== -->
      <!-- toggle and nav items -->
      <!-- ============================================================== -->
      <ul class="navbar-nav float-left mr-auto">
        <li class="nav-item d-none d-md-block">
          <a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar">
            <i class="mdi mdi-menu font-24 text-secondary"></i>
          </a>
        </li>
      </ul>
      <!-- ============================================================== -->
      <!-- Right side toggle and nav items -->
      <!-- ============================================================== -->
      <ul class="navbar-nav float-right">
        <!-- ============================================================== -->
        <!-- User profile and search -->
        <!-- ============================================================== -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="<%= asset_path("users/1.jpg") %>" alt="user" class="rounded-circle" width="31">
          </a>
          <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
            <span class="with-arrow"><span class="bg-white"></span></span>
            <%= link_to admins_edit_url, class: "dropdown-item" do %>
              <i class="fa fa-user m-r-5 m-l-5"></i> Profile
            <% end %>
            <%= link_to destroy_admin_session_url, class: "dropdown-item", method: :delete do %>
              <i class="fa fa-power-off m-r-5 m-l-5"></i> Logout
            <% end %>
          </div>
        </li>
        <!-- ============================================================== -->
        <!-- User profile and search -->
        <!-- ============================================================== -->
      </ul>
    </div>
  </nav>
</header>

app/views/shared/admins/_sidebar.html.erb
<aside class="left-sidebar">
  <!-- Sidebar scroll-->
  <div class="scroll-sidebar">
    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
      <ul id="sidebarnav">
        <!-- User Profile-->
        <li>
          <!-- User Profile-->
          <div class="user-profile d-flex no-block dropdown mt-3">
            <div class="user-pic">
              <img src="<%= asset_path("users/1.jpg") %>" alt="users" class="rounded-circle" width="40" />
            </div>
            <div class="user-content hide-menu ml-2">
              <a href="javascript:void(0)" class="" id="Userdd" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <h5 class="mb-0 user-name font-medium"><%= current_admin.name.present? ? current_admin.name : "Admin" %> <i class="fa fa-angle-down"></i></h5>
                <span class="op-5 user-email"><%= current_admin.email %></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Userdd">
                <%= link_to admins_edit_url, class: "dropdown-item" do %>
                  <i class="fa fa-user ml-1"></i> Profile
                <% end %>
                <%= link_to destroy_admin_session_url, class: "dropdown-item", method: :delete do %>
                  <i class="fa fa-power-off mr-1 ml-1"></i> Logout
                <% end %>
              </div>
            </div>
          </div>
          <!-- End User Profile-->
        </li>
        <li class="sidebar-item">
          <%= link_to admins_dashboards_path, class:"sidebar-link waves-effect waves-dark" do %>
            <i class="mdi mdi-view-dashboard"></i> <span class="hide-menu">Dashboard</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admins_categories_path, class:"sidebar-link waves-effect waves-dark" do %>
            <i class="mdi mdi-bookmark"></i> <span class="hide-menu">Categories</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admins_contacts_path, class:"sidebar-link waves-effect waves-dark" do %>
            <i class="mdi mdi-message-text"></i> <span class="hide-menu">Contacts</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admins_countries_path, class:"sidebar-link waves-effect waves-dark" do %>
            <i class="mdi mdi-flag"></i> <span class="hide-menu">Countries</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admins_genders_path, class:"sidebar-link waves-effect waves-dark" do %>
            <i class="mdi mdi-gender-male-female"></i> <span class="hide-menu">Genders</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admins_subscribers_path, class:"sidebar-link waves-effect waves-dark" do %>
            <i class="mdi mdi-account-multiple"></i> <span class="hide-menu">Subscribers</span>
          <% end %>
        </li>
        <li class="sidebar-item">
          <%= link_to admins_users_path, class:"sidebar-link waves-effect waves-dark" do %>
            <i class="mdi mdi-account-multiple"></i> <span class="hide-menu">Users</span>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- End Sidebar navigation -->
  </div>
  <!-- End Sidebar scroll-->
</aside>